name: user-web  #server name
port: ":8021"  # user-web server port
user_srv: # rpc user_srv
  host: 0.0.0.0
  port: 50051
jwt:
  sign_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICWgIBAAKBgGMQ9ZfXdY/TXcr9d1T1IHVRxXclDcvgREbApQVkdDbC3JtxsYdU
    XH9IZhcDms2UbQrwBYEIrhjgdWRHaqob6IBX9NG6uMrHA8sjwQCp6znz/IP7xkfR
    sIXU0XbCl1Iqu6b78wGLBFRYJYiKMNB/GmRaZQMiry5Q96Lp8I2A/R4dAgMBAAEC
    gYA0XwTWjsrRi/Xrl+979FKCcwYnJGmUvCycEr+qiB5/zKf/bS1i05BKoaWGyRsP
    T0YOIDFos4QGFrM4niCfaT2R4F86tL42Ih0fBP5wIPYU7fnBI24F+/YCHB9Ilb2Y
    EB7T4SvSqCqrKNP7I8kHlsZcGOQHtYq+dQiLdh17N4zuAQJBAMFYxi7K8jmHCbi3
    wLEY1V5uUp29+whxR2KxUIR4Tzbp/spzM1vbLIoCXykBbsy9DBB2J3kWL5BpR1AR
    zBK4YF0CQQCDKxLkOJn+rYeL5EgefVEITUeKV9q+fRqyXsYD6Lu1p+x/Wib4hDzO
    /G2609JOjdrQYfl83HT2nxzKHQzKhtjBAkB4bsmToApdVwXxL1Qxe9x8I5AGfa3+
    RkFG8lfLC/2boQl6JWPaVZ1aobuQmTnhAeif4FkaDX23IDyxXUSWbI5pAkB8VdlL
    gqfe9UkWfycp16p3TyHwboUIqngi+pmDXRqKAIq60Y89ZcRqhHfTcDTbh7YSb7zZ
    8fPhT0QwBkd4t0hBAkBL3NPp4jStQny6AtUzpX0oiTn3u3SoDuK3l4mKFMB818Lm
    5tCzow1dpbsqPM2yHV6w+/HQz/d+S/KjWfBSGrjm
    -----END RSA PRIVATE KEY-----
  pub_key: |
    -----BEGIN PUBLIC KEY-----
    MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGMQ9ZfXdY/TXcr9d1T1IHVRxXcl
    DcvgREbApQVkdDbC3JtxsYdUXH9IZhcDms2UbQrwBYEIrhjgdWRHaqob6IBX9NG6
    uMrHA8sjwQCp6znz/IP7xkfRsIXU0XbCl1Iqu6b78wGLBFRYJYiKMNB/GmRaZQMi
    ry5Q96Lp8I2A/R4dAgMBAAE=
    -----END PUBLIC KEY-----
sms:
  key: LTAI5tEEpaHuxKeLtDZsA8fe
  secret: nMqiVh0ysdfRNq8eWUHlKxB7N3JC1Z
  regionId: cn-hangzhou
redis:
  host: 121.37.232.8
  port: 6379